data:
  train:
    dataset: '../../dataset/fastmri/brain/singlecoil_train/'
    num_samples: 10000
    mri_type: "FLAIR"
    num_workers: 4


model:
  dim_in: 2
  dim_hidden: 256
  dim_out: 1
  latent_dim: 256
  num_layers: 5
  w0: 1.0
  w0_initial: 30.0
  use_bias: True
  dropout: 0.1
  encoder_type: "custom"
  encoder_path: './models/custom_encoder.pth'
  outer_patch_size: 32
  inner_patch_size: 16
  
training:
  lr: 0.0001
  batch_size: 400
  epochs: 10000
  output_dir: "./output"
  output_name: "refactored"
  optimizer: "Adam"
  save_interval: 100
  model:
    continue_training: False
