data:
  train:
    dataset: 'C:\Users\jan\Documents\python_files\adlm\data\brain\singlecoil_train\processed_files'
    mri_type: "FLAIR"
    num_workers: 4
    num_samples: 0
  val:
    dataset: 'C:\Users\jan\Documents\python_files\adlm\data\brain\singlecoil_val\processed_files'
    mri_type: "FLAIR"
    num_workers: 4
    num_samples: 0

training:
  criterion: "MSE"
  optimizer: "Adam"
  lr: 0.0001
  batch_size: 2048
  epochs: 10000
  output_dir: "./output"
  output_name: "Standard"
  save_interval: 25

model:
  outer_patch_size: 24
  inner_patch_size: 16
  siren_patch_size: 24


