data:
  acceleration: 6
  center_fraction: 0.1
  train:
    dataset: '../../dataset/fastmri/brain/singlecoil_train/processed_files'
    mri_type: "FLAIR"
    num_workers: 4
    num_samples: 50
  val:
    dataset: '../../dataset/fastmri/brain/singlecoil_val/processed_files'
    mri_type: "FLAIR"
    num_workers: 4
    num_samples: 50

training:
  criterion: "MSE"
  optimizer: "Adam"
  lr: 0.0001
  batch_size: 10
  epochs: 10000
  output_dir: "./output/test123"
  output_name: "Standard"
  save_interval: 25

model:
  outer_patch_size: 32
  inner_patch_size: 16
  siren_patch_size: 24


