data:
  train:
    dataset: '../../dataset/fastmri/brain/singlecoil_train/processed_v2'
    mri_type: "FLAIR"
    num_workers: 4
    tmp_info_str: cf0.05_acc6_morlet
  val:
    dataset: '../../dataset/fastmri/brain/singlecoil_val/processed_v2'
    mri_type: "FLAIR"
    num_workers: 4
    num_samples: 50

model:
  dim_in: 2
  dim_hidden: 256
  dim_out: 1
  latent_dim: 256
  num_layers: 5
  w0: 1.0
  w0_initial: 30.0
  use_bias: True
  dropout: 0.1
  encoder_type: "custom"
  encoder_path: './models/custom_encoder.pth'
  outer_patch_size: 32
  inner_patch_size: 16
  siren_patch_size: 24
  activation: "sine"
  
training:
  lr: 0.0001
  batch_size: 400
  epochs: 10000
  output_dir: "./output"
  output_name: "Standard"
  optimizer: "Adam"
  save_interval: 25
  logging: True
  criterion: "MSE"
  model:
    continue_training: False
