data:
  acceleration: 6
  center_fraction: 0.1
  train:
    dataset: 'C:/Users/jan/Documents/python_files/adlm/data/brain/singlecoil_train/processed_files_complex'
    mri_type: "FLAIR"
    num_workers: 1
    num_samples: 3
  val:
    dataset: 'C:/Users/jan/Documents/python_files/adlm/data/brain/singlecoil_train/processed_files_complex'
    mri_type: "FLAIR"
    num_workers: 1
    num_samples: 3

training:
  criterion: "MSE"
  optimizer: "Adam"
  lr: 0.0001
  batch_size: 10
  epochs: 10000
  output_dir: "./output/test123"
  output_name: "Standard"
  save_interval: 25

model:
  outer_patch_size: 32
  inner_patch_size: 16
  siren_patch_size: 24


