data:
  train:
    dataset: '../../dataset/fastmri/brain/singlecoil_train/processed_files'
    mri_type: "FLAIR"
    num_workers: 4
    num_samples: null
  val:
    dataset: '../../dataset/fastmri/brain/singlecoil_val/processed_files'
    mri_type: "FLAIR"
    num_workers: 4
    num_samples: 50

training:
  criterion: "MSE"
  optimizer: "Adam"
  lr: 0.0001
  batch_size: 2048
  epochs: 10000
  output_dir: "./output/perceptual_encoder"
  output_name: "Standard"
  save_interval: 25

model:
  outer_patch_size: 24
  inner_patch_size: 16
  siren_patch_size: 24


