data:
  acceleration: 6
  center_fraction: 0.05
  train:
    dataset: '../../dataset/fastmri/brain/singlecoil_train/processed_files'
    mri_type: "FLAIR"
    num_workers: 4
  val:
    dataset: '../../dataset/fastmri/brain/singlecoil_val/processed_files'
    mri_type: "FLAIR"
    num_workers: 4
    num_samples: 5

model:
  dim_in: 2
  dim_hidden: 256
  dim_out: 1
  latent_dim: 256
  num_layers: 5
  w0: 1.0
  w0_initial: 30.0
  use_bias: True
  dropout: 0.1
  encoder_type: "custom"
  encoder_path: './models/custom_encoder.pth'
  outer_patch_size: 32
  inner_patch_size: 16
  siren_patch_size: 24
  activation: "sine"
  
training:
  lr: 0.0001
  batch_size: 400
  epochs: 10000
  output_dir: "./output"
  output_name: "modulated_siren"
  optimizer: "Adam"
  save_interval: 25
  logging: True
  criterion: "MSE"